name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # or 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Change if needed

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm test   # Remove or comment out if no test script

      - name: Trigger Render Deployment
        run: |
          curl -X POST https://study-prisma.onrender.com/
